[pytest]
pythonpath = .
markers = 
    jwt: json web token tests
    unit: mark test as unit ones.
    integration: mark tests as integration ones.
    auth: mark test as related to authentication.
    protected: mark test as related to protected route.